<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active processes:' => '進行中:',
    'All dumps successfully removed.' => '所有備份已刪除.',
    'Are you sure?' => '您確定?',
    'Create dump' => '創建備份',
    'Create time' => '創建時間',
    'Custom dump preset' => '自定義備份',
    'Custom restore preset' => '',
    'DB manager' => '資料庫管理',
    'Database' => '資料庫',
    'Delete' => '刪除',
    'Delete all' => '刪除全部',
    'Delete from storage' => '從存儲盤中刪除',
    'Download' => '下載',
    'Dump deleted from storage.' => '備份已刪除',
    'Dump deleted successfully.' => '備份刪除成功',
    'Dump failed.' => '備份失敗',
    'Dump only schema' => '僅備份表',
    'Dump request invalid.' => '備份請求不合法',
    'Dump successfully created.' => '備份成功創建',
    'Dump successfully restored.' => '備份成功存儲',
    'Dump uploaded to storage.' => '備份成功上傳',
    'Error deleting dump.' => '刪除備份出錯',
    'Error deleting dumps.' => '刪除備份出錯',
    'Name' => '名稱',
    'Process complete!' => '進程完成',
    'Process running with pid={pid}' => '進程正在跑中 pid={pid}',
    'Restore' => '恢復',
    'Restore failed.' => '恢復失敗',
    'Run in background' => '在後台進行',
    'Size' => '大小',
    'Type' => '類型',
    'Upload to storage' => '上傳到存儲',
    'gzip' => 'GZIP',
    'File Name' => '文件名稱',
];